<script src="<?=base_url('js/jquery.js')?>"></script>
<script src="<?=base_url('js/popper.min.js')?>"></script>
<script src="<?=base_url('js/bootstrap.min.js')?>"></script>
<!--Revolution Slider-->
<script src="<?=base_url('plugins/revolution/js/jquery.themepunch.revolution.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/jquery.themepunch.tools.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.actions.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.carousel.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.kenburn.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.migration.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.navigation.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.parallax.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.slideanims.min.js')?>"></script>
<script src="<?=base_url('plugins/revolution/js/extensions/revolution.extension.video.min.js')?>"></script>
<script src="<?=base_url('js/main-slider-script.js')?>"></script>
<!--Revolution Slider-->

<script src="<?=base_url('js/jquery-ui.js')?>"></script>
<script src="<?=base_url('js/jquery.fancybox.js')?>"></script>
<script src="<?=base_url('js/owl.js')?>"></script>
<script src="<?=base_url('js/wow.js')?>"></script>
<script src="<?=base_url('js/appear.js')?>"></script>
<script src="<?=base_url('js/script.js')?>"></script>